// <auto-generated />
namespace PhoneBookMVCApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig_udpated_people_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_udpated_people_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202312261140365_mig_udpated_people_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
